version: '3'
services:
  web:
    image: chat-app
    build: .
    ports:
      - "4000"
    environment:
      - PORT=4000
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - web
